### PR TITLE
BRANCH-US13 generate annual financial reports 29

### PR DESCRIPTION
**Pull request by JRB958**
in this PR: 
- use the UI that was designed in #135 to implement api calls and receive the financial data dynamically from the backend instead of hard coding a sample as before.

the user story #29 is not fully completed, but the available features will be merged for the demo a

related US: 
#29

### CODE REVIEW

**Comment by NicholasWahome** [comment]
Screenshot 2024-03-21 at 4 33 47 PM
@JRB958 Please justify in comment why the third test in this pr breaks

**Comment by JRB958** [comment]
This is an outdated test file for an updated component, the component will be tested separately after finishing all the tasks needed.

**Review by patrickmac3 — APPROVED** [review]
added finance section to the user dashboard. (different for both public and company profiles) 
displays the unit fee's and operational expenses for the company 
display property fee's for the public user

**Review by NicholasWahome — APPROVED** [review]
For this specific pull request it's okay, but please add test for components as part of the same pull request for future pull requests. 
Overall this is the only issue pertaining to this pull requesting everything else follows the code management standard.

**Pull request merged**
