### PR TITLE
Branch us12 record operational budget cost 28

### PR DESCRIPTION
**Pull request by JRB958**
in this PR: 

- company employees can have an operational page that allows them to enter costs and compare them to unit condo fees. 
- this PR only has UI template functionality will be added later when time permits. 

-small bug: low severity and priority: the "operation" on the navigation bar doesn't show right away, requires navigation on the website to show us (briefly not visible to company and briefly visible to public) which is not the intended design.

related us:
#28

### CODE REVIEW

**Review by NicholasWahome — CHANGES_REQUESTED** [review]
Uncommit the testing.yml file or make sure this branch is up to date with development

**Comment by JRB958** [comment]
ok ill remove it, but I merge development into this branch before the pr. the merge brought back the testing file

**Review by NicholasWahome — APPROVED** [review]
Appropriate changes were made. 
This is the merging of a User story into development which is perfect!

**Review by MinhDuc1711 — APPROVED** [review]
Minor changes to registration key UI and financial UI
Added operation page, successfully limited it to only company users
Updated ReadMe with current code management metrics
Updated good testing

**Pull request merged**
