### PR TITLE
Task us9 sending registration keys doesnt work on all devices 169

### PR DESCRIPTION
**Pull request by patrickmac3**
- updated send_registration_key to include unit information and use template setup in mailtrap 
- updated views for creating registration keys to pass key object to send_registration_key method. 
- updated settings for email sending

### CODE REVIEW

**Review by JRB958 — APPROVED** [review]
Updates reflect the solution to the problem, and the email template was well made. Nothing to add or request

**Review by JRB958 — CHANGES_REQUESTED** [review]
please check the backend tests

**Review by JRB958 — APPROVED** [review]
Request was met! Thanks! 

Registration key changes are done well!

**Review by NicholasWahome — APPROVED** [review]
Follows our coding standards!

**Pull request merged**
